feat: abortable request hook
equinor/fusion-api pull request #628
Opened 2021-08-20 06:41 UTC by tobiasny

Hook for making HTTP requests abortable.

Utilizes the abortController provided by fusion-api.

2021-08-20 08:58 UTC, odinr commented on src/hooks/useAbortableRequest.ts
> + * Hook for making HTTP requests abortable
missing example https://typedoc.org/guides/doccomments/#code-blocks

2021-08-20 09:00 UTC, odinr commented on src/hooks/useAbortableRequest.ts
> +export default <T extends Array<unknown>>(
use 
```ts
export const NAMED_EXPORT = () => {...}
export default NAMED_EXPORT
```

2021-08-20 09:01 UTC, odinr commented on src/hooks/useAbortableRequest.ts
> + * Hook for making HTTP requests abortable
explain arguments and type arguments
https://typedoc.org/guides/doccomments/#%40param-%3Cparam-name%3E

2021-08-20 09:02 UTC, odinr commented on src/index.ts
> +export { default as useAbortableRequest } from './hooks/useAbortableRequest';
use named export

2021-08-20 11:04 UTC, odinr requested changes
add more docs

2021-08-23 08:41 UTC, tobiasny commented
Add docs

2022-05-19 06:46 UTC, odinr approved these changes

2022-05-19 06:48 UTC, merged