Feature/data export api
equinor/fusion-api pull request #630
Opened 2021-09-13 06:32 UTC by jaysencpp

2021-09-20 10:39 UTC, jaysencpp commented on src/http/hooks/dataExport/useExcelExport.ts
> +                console.error(err);
Handle this? Just return it from the hook?

2021-09-30 11:48 UTC, odinr requested changes

2021-09-30 11:48 UTC, odinr commented on src/http/apiClients/FusionClient.ts
> +
add tsdoc

2021-09-30 11:48 UTC, odinr commented on src/http/apiClients/FusionClient.ts
> +
add tsdoc

2021-09-30 11:48 UTC, odinr commented on src/http/hooks/dataExport/useExcelExport.ts
> +        async (data: { sheets: Sheet[] }) => {
remove async and type hint return type

2021-09-30 11:48 UTC, odinr commented on src/http/hooks/dataExport/useExcelExport.ts
> +            return await fusion.getExcelStatusInterval({
no point awaiting, return the method

2021-11-16 08:01 UTC, merged